package daemon

import (
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"

	"github.com/drn/argus/internal/agent"
	"github.com/drn/argus/internal/db"
	"github.com/drn/argus/internal/heraadopt"
	"github.com/drn/argus/internal/model"
)

// SystemTaskID is the sentinel "from" used for daemon-originated inbox
// messages. It is intentionally not a digit-only string so it can never
// collide with a real task ID generated by db.generateID.
const SystemTaskID = "argus:system"

// liveTasksAtShutdownFilename is the file written at daemon shutdown to record
// which tasks had live PTY sessions. Replayed as ARGUS_BOUNCED inbox messages
// on the next startup so hera workers can auto-resume without user intervention.
const liveTasksAtShutdownFilename = "live-tasks-at-shutdown.json"

func liveTasksAtShutdownPath(dataDir string) string {
	return filepath.Join(dataDir, liveTasksAtShutdownFilename)
}

// writeLiveTasksFile atomically writes the set of currently-running task IDs
// to disk. Called in cleanup() just before StopAll so the snapshot reflects
// live sessions. Uses write-then-rename for atomicity: a SIGKILL mid-write
// leaves either the old file or a complete new one, never a partial payload.
// No-op when the runner has no active sessions. Accepts the agent.SessionProvider
// interface (not concrete *agent.Runner) so it works whether the daemon owns an
// in-process runner or a supervisor-client — though in supervisor mode the daemon
// skips this call entirely (agents survive the bounce, so there's nothing to
// signal; see Daemon.cleanup).
func writeLiveTasksFile(runner agent.SessionProvider, dataDir string) error {
	ids := runner.Running()
	if len(ids) == 0 {
		return nil
	}

	data, err := json.Marshal(ids)
	if err != nil {
		return fmt.Errorf("marshal live tasks: %w", err)
	}

	path := liveTasksAtShutdownPath(dataDir)
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return fmt.Errorf("write live tasks tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp) //nolint:errcheck
		return fmt.Errorf("rename live tasks: %w", err)
	}
	slog.Info("bounce: wrote live-tasks file", "count", len(ids))
	return nil
}

// replayBounceSignals reads the live-tasks-at-shutdown file (if present) and
// posts an ARGUS_BOUNCED note into each task's inbox. Called in Serve() after
// DB is ready and stale sessions are reconciled, before accepting connections,
// so agents that auto-resume on startup see the signal on their first inbox
// poll. Skips tasks that no longer exist or are archived. Removes the file on
// completion so signals replay exactly once.
func replayBounceSignals(database *db.DB, dataDir string) error {
	path := liveTasksAtShutdownPath(dataDir)
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return fmt.Errorf("read live-tasks file: %w", err)
	}

	var ids []string
	if err := json.Unmarshal(data, &ids); err != nil {
		// Corrupted file — remove it so we don't block every future startup.
		slog.Warn("bounce: corrupt live-tasks file, removing", "err", err)
		os.Remove(path) //nolint:errcheck
		return nil
	}

	sent := sendBounceSignals(database, ids)

	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		slog.Warn("bounce: failed to remove live-tasks file", "err", err)
	}
	slog.Info("bounce: replay complete", "total", len(ids), "sent", sent)
	return nil
}

// ReconcileOnStartup runs the daemon's once-per-boot reconciliation of DB
// session state against reality. Serve calls it after the singleton takeover
// and before the listener accepts connections; it is also the seam tests drive
// directly (so they never bind a socket or touch the live daemon). It has two
// modes, selected by whether a supervisor-client is mounted:
//
//   - In-process (supervisor OFF, d.supClient == nil): byte-identical to the
//     pre-P3 path. The previous daemon StopAll'd every agent, so EVERY InProgress
//     row is an orphan → flip all to InReview, then replay ARGUS_BOUNCED from the
//     live-tasks file the previous cleanup wrote.
//
//   - Supervisor (ON, d.supClient != nil): the supervisor kept the agents alive
//     across the daemon bounce, so we RE-ATTACH instead of orphaning. See
//     reattachSupervised — it queries the supervisor's live set, re-arms each
//     live session, and flips only the true orphans.
//
// heraadopt.ReconcileBindings runs in BOTH modes: it is keyed on task-row
// existence (not session liveness), so a re-attached task's row exists and its
// hera binding survives for free — M4 composes with re-attach without change.
func (d *Daemon) ReconcileOnStartup() {
	if d.supClient != nil {
		d.reattachSupervised()
	} else {
		if n, err := agent.ReconcileStaleSessions(d.db); err != nil {
			slog.Warn("reconcile stale sessions failed", "err", err)
		} else if n > 0 {
			slog.Info("reconciled stale sessions", "count", n)
		}
	}

	// Sweep hera bindings whose argus task row no longer exists — the row was
	// deleted while the daemon was down so the delete-cascade never severed the
	// binding (risk e). End them with reason "task_missing". Idempotent; runs
	// every boot in both modes.
	if n, err := heraadopt.ReconcileBindings(d.db); err != nil {
		slog.Warn("reconcile hera bindings failed", "err", err)
	} else if n > 0 {
		slog.Info("reconciled hera bindings", "ended", n)
	}

	// In-process mode: emit ARGUS_BOUNCED for every task that had a live session
	// when the previous daemon exited (read from the live-tasks file). Supervisor
	// mode does NOT use the file — re-attached agents were never interrupted, and
	// the true-orphan signals are sent inside reattachSupervised against the live
	// set.
	//
	// Supervisor mode (the P4 default) instead DISCARDS any stale live-tasks file.
	// The P4 default flip means the very first supervisor-mode start can inherit a
	// file written by the last OFF-mode (in-process) run: those agents already
	// died with the old daemon and reattachSupervised has just orphaned + signalled
	// their rows exactly once. Leaving the file on disk would let a later ON→OFF
	// rollback replay that now-stale snapshot and double-signal long-resolved
	// tasks, so we remove it here. Supervisor-mode cleanup never writes the file,
	// so removing it is purely defensive against the OFF→ON transition.
	if d.supClient == nil {
		if err := replayBounceSignals(d.db, db.DataDir()); err != nil {
			slog.Warn("bounce: replay failed", "err", err)
		}
	} else {
		discardStaleLiveTasksFile(db.DataDir())
	}
}

// discardStaleLiveTasksFile removes a leftover live-tasks-at-shutdown file in
// supervisor mode. It only ever exists across an OFF→ON transition (the P4
// default flip): supervisor-mode cleanup never writes it. Removing it stops a
// later ON→OFF rollback from replaying a stale snapshot. A missing file is the
// common, non-error case.
func discardStaleLiveTasksFile(dataDir string) {
	path := liveTasksAtShutdownPath(dataDir)
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		slog.Warn("bounce: failed to discard stale live-tasks file in supervisor mode", "err", err)
	}
}

// reattachSupervised is the supervisor-mode (P3) startup reconcile. The
// supervisor is a separate long-lived process that owns the agent PTYs, so a
// daemon bounce leaves the agents running. This:
//
//  1. Queries the supervisor's live task-ID set (authoritative — the supervisor
//     owns the sessions). If the query fails (nil — distinct from an empty
//     authoritative set), it SKIPS reconciliation entirely: flipping live agents
//     to InReview on an unconfirmed empty set would be a false termination. The
//     next bounce or the TUI tick reconciles once the supervisor answers. This
//     mirrors the TUI's runningIDs!=nil guard (daemon-rpc.md).
//
//  2. RE-ATTACHES each live session by calling Get on the supervisor-client.
//     Get opens a stream (StreamHeader{Since:0}) so the supervisor replays its
//     ring and the daemon's local ring rebuilds — AND it arms the supervisor-
//     client's exit relay (connectStream → removeSession → OnSessionExit →
//     handleSessionExit). The armed relay is LOAD-BEARING for #707 across the
//     bounce: without it, a re-attached session that later exits cleanly while no
//     TUI/PWA client is attached would never reach handleSessionExit and the task
//     would never flip to Complete.
//
//  3. Flips ONLY the true orphans (InProgress rows the supervisor does NOT report
//     alive — e.g. the supervisor also restarted/crashed) to InReview, leaving
//     re-attached tasks InProgress.
//
//  4. Posts ARGUS_BOUNCED to those true orphans only (they actually lost their
//     session); re-attached agents were never interrupted and get nothing. In the
//     pure re-attach case (the supervisor kept everything), this is a no-op.
func (d *Daemon) reattachSupervised() {
	live := d.supClient.Running()
	if live == nil {
		// nil ⇒ the ListSessions RPC to the supervisor failed; we cannot tell live
		// from orphan. Do NOT flip — wrongly InReview-ing still-alive agents is a
		// false termination. (An authoritative empty set is non-nil, so a genuine
		// "no sessions" case still reconciles.)
		slog.Warn("reattach: supervisor live-set query failed; skipping reconcile to avoid false termination")
		return
	}

	liveSet := make(map[string]bool, len(live))
	for _, id := range live {
		liveSet[id] = true
	}

	// Re-attach each live session: rebuild the local ring + arm the exit relay.
	reattached := 0
	for id := range liveSet {
		if sess := d.supClient.Get(id); sess != nil {
			reattached++
		}
	}
	slog.Info("reattach: re-attached live supervisor sessions", "reattached", reattached, "live", len(liveSet))

	// Restore any re-attached worker stranded in in_review by a prior roll or
	// reconcile but genuinely alive and working again (BUG-B). The helper is
	// worker-kind only, fires only on an in_review task, and LEAVES genuinely-
	// finished workers (ready_to_close / role-status done|failed) in in_review,
	// preserving the #707 / BUG-050 close-out invariant. Scoped to liveSet —
	// the true orphans (handled below) deliberately flip the other way.
	revived := 0
	for id := range liveSet {
		if ok, err := d.db.ReviveHeraWorkerToInProgress(id); err != nil {
			slog.Warn("reattach: revive-to-in_progress failed", "task", id, "err", err)
		} else if ok {
			revived++
		}
	}
	if revived > 0 {
		slog.Info("reattach: restored stranded live workers to in_progress", "count", revived)
	}

	// Flip only the true orphans; re-attached (live) tasks stay InProgress.
	orphans, err := agent.ReconcileStaleSessionsExcept(d.db, liveSet)
	if err != nil {
		slog.Warn("reattach: reconcile stale sessions failed", "err", err)
		return
	}
	if len(orphans) > 0 {
		slog.Info("reattach: reconciled true orphans", "count", len(orphans))
	}

	// Signal ARGUS_BOUNCED to the true orphans only.
	if sent := sendBounceSignals(d.db, orphans); sent > 0 {
		slog.Info("reattach: signalled orphans", "sent", sent)
	}
}

// sendBounceSignals posts an ARGUS_BOUNCED note into each given task's inbox,
// skipping tasks that no longer exist or are archived. Returns the number of
// signals actually sent. Two callers share it:
//
//   - replayBounceSignals (in-process mode): feeds the IDs read from the
//     live-tasks-at-shutdown file (every session alive when the daemon stopped).
//   - the supervisor-mode startup reconcile (P3): feeds ONLY the true-orphan IDs
//     (InProgress rows the supervisor no longer reports alive). Re-attached
//     agents were never interrupted, so they are deliberately NOT signalled.
//
// Per-task send failures are logged and skipped so one bad row never blocks the
// rest of the batch.
func sendBounceSignals(database *db.DB, ids []string) int {
	sent := 0
	for _, id := range ids {
		t, getErr := database.Get(id)
		if getErr != nil || t == nil || t.Archived {
			slog.Info("bounce: skipping task", "task", id)
			continue
		}
		msg := &model.TaskMessage{
			From: SystemTaskID,
			To:   id,
			Kind: model.KindNote,
			Body: `{"type":"ARGUS_BOUNCED"}`,
		}
		if _, sendErr := database.InsertSystemMessage(msg); sendErr != nil {
			slog.Warn("bounce: failed to send signal", "task", id, "err", sendErr)
			continue
		}
		sent++
	}
	return sent
}
