package daemon

import (
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"

	"github.com/drn/argus/internal/agent"
	"github.com/drn/argus/internal/db"
	"github.com/drn/argus/internal/model"
)

// SystemTaskID is the sentinel "from" used for daemon-originated inbox
// messages. It is intentionally not a digit-only string so it can never
// collide with a real task ID generated by db.generateID.
const SystemTaskID = "argus:system"

// liveTasksAtShutdownFilename is the file written at daemon shutdown to record
// which tasks had live PTY sessions. Replayed as ARGUS_BOUNCED inbox messages
// on the next startup so hera workers can auto-resume without user intervention.
const liveTasksAtShutdownFilename = "live-tasks-at-shutdown.json"

func liveTasksAtShutdownPath(dataDir string) string {
	return filepath.Join(dataDir, liveTasksAtShutdownFilename)
}

// writeLiveTasksFile atomically writes the set of currently-running task IDs
// to disk. Called in cleanup() just before StopAll so the snapshot reflects
// live sessions. Uses write-then-rename for atomicity: a SIGKILL mid-write
// leaves either the old file or a complete new one, never a partial payload.
// No-op when the runner has no active sessions.
func writeLiveTasksFile(runner *agent.Runner, dataDir string) error {
	ids := runner.Running()
	if len(ids) == 0 {
		return nil
	}

	data, err := json.Marshal(ids)
	if err != nil {
		return fmt.Errorf("marshal live tasks: %w", err)
	}

	path := liveTasksAtShutdownPath(dataDir)
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return fmt.Errorf("write live tasks tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp) //nolint:errcheck
		return fmt.Errorf("rename live tasks: %w", err)
	}
	slog.Info("bounce: wrote live-tasks file", "count", len(ids))
	return nil
}

// replayBounceSignals reads the live-tasks-at-shutdown file (if present) and
// posts an ARGUS_BOUNCED note into each task's inbox. Called in Serve() after
// DB is ready and stale sessions are reconciled, before accepting connections,
// so agents that auto-resume on startup see the signal on their first inbox
// poll. Skips tasks that no longer exist or are archived. Removes the file on
// completion so signals replay exactly once.
func replayBounceSignals(database *db.DB, dataDir string) error {
	path := liveTasksAtShutdownPath(dataDir)
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return fmt.Errorf("read live-tasks file: %w", err)
	}

	var ids []string
	if err := json.Unmarshal(data, &ids); err != nil {
		// Corrupted file — remove it so we don't block every future startup.
		slog.Warn("bounce: corrupt live-tasks file, removing", "err", err)
		os.Remove(path) //nolint:errcheck
		return nil
	}

	sent := 0
	for _, id := range ids {
		t, getErr := database.Get(id)
		if getErr != nil || t == nil || t.Archived {
			slog.Info("bounce: skipping task", "task", id)
			continue
		}
		msg := &model.TaskMessage{
			From: SystemTaskID,
			To:   id,
			Kind: model.KindNote,
			Body: `{"type":"ARGUS_BOUNCED"}`,
		}
		if _, sendErr := database.InsertSystemMessage(msg); sendErr != nil {
			slog.Warn("bounce: failed to send signal", "task", id, "err", sendErr)
			continue
		}
		sent++
	}

	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		slog.Warn("bounce: failed to remove live-tasks file", "err", err)
	}
	slog.Info("bounce: replay complete", "total", len(ids), "sent", sent)
	return nil
}
